FROM node:latest

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY .sequelizerc .sequelizerc

RUN npm install

COPY dist ./dist
COPY database ./database

ENTRYPOINT [ "npm", "run", "docker:migrate" ]
